name: Action Sample
description: aaa

inputs:
  your-name:
    description: sample input
    required: true
    type: string

runs:
  using: composite
  steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: echo
      shell: bash
      env:
        YOUR_NAME: ${{ inputs.your-name }}
      run: echo "Hello, ${YOUR_NAME}!"
