name: Workflow Sample

on:
  workflow_dispatch:
  push:

jobs:
  setup:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    outputs:
      NAME: ${{ steps.echo-out.outputs.NAME }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: echo out
        id: echo-out
        run: echo "NAME=foo" >> $GITHUB_OUTPUT

  use-custom-action:
    needs: setup
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: run
        uses: ./.github/actions/action-sample
        with:
          your-name: ${{ needs.setup.outputs.NAME }}
